<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 3.4.0
 * @copyright Copyright (c) 2015, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['UniversalServerModule.name'] = "Módulo Universal";
$lang['UniversalServerModule.add_module_row'] = "Añadir Producto";
$lang['UniversalServerModule.manage.module_rows_title'] = "Productos";
$lang['UniversalServerModule.manage.module_rows_heading.name'] = "Etiqueta del Producto";
$lang['UniversalServerModule.manage.module_rows_heading.options'] = "Opciones";
$lang['UniversalServerModule.manage.module_rows.delete'] = "Borrar";
$lang['UniversalServerModule.manage.module_rows.confirm_delete'] = "¿Seguro que desea borrar este producto?";
$lang['UniversalServerModule.add_row.box_title'] = "Añadir Producto";
$lang['UniversalServerModule.add_row.name'] = "Nombre";
$lang['UniversalServerModule.add_row.notice_code'] = "Código HTTP";
$lang['UniversalServerModule.add_row.package_field_btn'] = "Opcion de Agregar Paquetes";
$lang['UniversalServerModule.add_row.package_field_label'] = "Label";
$lang['UniversalServerModule.add_row.package_field_name'] = "Nombre";
$lang['UniversalServerModule.add_row.package_field_required'] = "Requerido";
$lang['UniversalServerModule.add_row.package_field_encrypt'] = "Cifrar";
$lang['UniversalServerModule.add_row.remove_package_field'] = "Eliminar";
$lang['UniversalServerModule.add_row.package_email_from'] = "Desde el correo electrónico";
$lang['UniversalServerModule.add_row.package_email_subject'] = "Sujeto";
$lang['UniversalServerModule.add_row.service_title'] = "Opciones de Servidor";
$lang['UniversalServerModule.add_row.service_field_btn'] = "Añadir opción de servicio";
$lang['UniversalServerModule.add_row.service_field_label'] = "Etiqueta";
$lang['UniversalServerModule.add_row.service_field_values'] = "Valores";
$lang['UniversalServerModule.add_row.service_field_required'] = "Requerido";
$lang['UniversalServerModule.add_row.service_field_encrypt'] = "Encriptar";
$lang['UniversalServerModule.add_row.remove_service_field'] = "Eliminar";
$lang['UniversalServerModule.add_row.service_rules'] = "Reglas de entrada";
$lang['UniversalServerModule.add_row.service_email_from'] = "Del Email";
$lang['UniversalServerModule.add_row.service_email_subject'] = "Sujeto";
$lang['UniversalServerModule.add_row.service_email_html'] = "HTML";
$lang['UniversalServerModule.add_row.service_email_text'] = "Texto";
$lang['UniversalServerModule.add_row.add_btn'] = "Agregar Producto";
$lang['UniversalServerModule.edit_row.module_title'] = "Opciones de módulo";
$lang['UniversalServerModule.edit_row.name'] = "Nombre";
$lang['UniversalServerModule.edit_row.notice_name'] = "Aviso";
$lang['UniversalServerModule.edit_row.notice_notice'] = "

Publicar URL / Email
";
$lang['UniversalServerModule.edit_row.notice_response'] = "Respuesta Contiene";
$lang['UniversalServerModule.edit_row.email_notification'] = "Notificación por correo electrónico";
$lang['UniversalServerModule.edit_row.package_field_btn'] = "Añadir Opción de Paquete";
$lang['UniversalServerModule.edit_row.package_field_label'] = "Etiqueta";
$lang['UniversalServerModule.edit_row.package_field_type'] = "Tipo";
$lang['UniversalServerModule.edit_row.package_field_values'] = "Valores";
$lang['UniversalServerModule.edit_row.package_field_required'] = "Obligatario";
$lang['UniversalServerModule.edit_row.package_field_encrypt'] = "Encrypt";
$lang['UniversalServerModule.edit_row.remove_package_field'] = "Eliminar";
$lang['UniversalServerModule.edit_row.package_rules'] = "Reglas de entrada";
$lang['UniversalServerModule.edit_row.package_email_from'] = "Del Email";
$lang['UniversalServerModule.edit_row.package_email_subject'] = "Asunto";
$lang['UniversalServerModule.edit_row.package_email_html'] = "HTML";
$lang['UniversalServerModule.edit_row.package_email_text'] = "Texto";
$lang['UniversalServerModule.edit_row.service_title'] = "Opciones de Servicio";
$lang['UniversalServerModule.edit_row.service_field_label'] = "Etiqueta";
$lang['UniversalServerModule.edit_row.service_field_type'] = "Tipo";
$lang['UniversalServerModule.edit_row.service_field_values'] = "Valores";
$lang['UniversalServerModule.edit_row.remove_service_field'] = "Remover";
$lang['UniversalServerModule.edit_row.service_rules'] = "Reglas de Entrada";
$lang['UniversalServerModule.edit_row.service_email_subject'] = "Asunto";
$lang['UniversalServerModule.edit_row.service_email_html'] = "HTML";
$lang['UniversalServerModule.edit_row.service_email_text'] = "Texto";
$lang['UniversalServerModule.edit_row.add_btn'] = "Editar Producto";
$lang['UniversalServerModule.getpackagenotices.add'] = "Añadir";
$lang['UniversalServerModule.getpackagenotices.edit'] = "Editar";
$lang['UniversalServerModule.getservicenotices.add'] = "Añadir";
$lang['UniversalServerModule.getservicenotices.suspend'] = "Suspender";
$lang['UniversalServerModule.getservicenotices.cancel'] = "Cancelar";
$lang['UniversalServerModule.getservicenotices.renew'] = "Renovar";
$lang['UniversalServerModule.getservicenotices.package_change'] = "Cambios de Paquete";
$lang['UniversalServerModule.getfieldtypes.text'] = "Texto";
$lang['UniversalServerModule.getfieldtypes.textarea'] = "Area de Texto";
$lang['UniversalServerModule.getfieldtypes.password'] = "Contraseña";
$lang['UniversalServerModule.getfieldtypes.radio'] = "Radio
";
$lang['UniversalServerModule.getfieldtypes.checkbox'] = "Checkbox";
$lang['UniversalServerModule.getfieldtypes.secret'] = "Secreto";
$lang['UniversalServerModule.true'] = "Si";
$lang['UniversalServerModule.false'] = "No";
$lang['UniversalServerModule.getPackageFields.empty_module_row'] = "No existen productos Universales. <a href=\"%1\$s\">Crear uno.</a>"; // %1$s is the URI to add a product for the universal module
$lang['UniversalServerModule.!error.package_notice_add.failed'] = "El módulo no pudo comunicarse con el servidor remoto al intentar crear el paquete.
";
$lang['UniversalServerModule.!error.package_notice_edit.failed'] = "El módulo no comunicarse con el servidor remoto cuando attemptined para actualizar el paquete.";
$lang['UniversalServerModule.!error.service_notice_cancel.failed'] = "El módulo falló la comunicación con el servidor remoto al intentar cancelar el servicio.";
$lang['UniversalServerModule.!error.service_notice_suspend.failed'] = "La comunicación con el modulo fallo cuando el servidor remoto realizo la acción de suspender el servicio.";
$lang['UniversalServerModule.!error.service_notice_unsuspend.failed'] = "El módulo no comunicarse con el servidor remoto al intentar reactivar el servicio.";
$lang['UniversalServerModule.!error.package_field.required'] = "%1\$s se requiere."; // %1$s is the label for the required package field
$lang['UniversalServerModule.!error.service_field.required'] = "%1\$s es requerido."; // %1$s is the label for the required service field
$lang['UniversalServerModule.!error.name.empty'] = "Se requiere un nombre para el producto.";
$lang['UniversalServerModule.!error.package_email_from.required'] = "Se requiere la dirección del remitente para la notificación de correo electrónico de paquetes.";
$lang['UniversalServerModule.!error.module_row.invalid'] = "Debe especificar un producto del módulo universal.";
$lang['UniversalServerModule.manage.module_rows_no_results'] = "No hay productos";
$lang['UniversalServerModule.!tooltip.option_heading_field_type'] = "Este es el tipo de campo de formulario que se mostrará.";
$lang['UniversalServerModule.!tooltip.option_heading_field_required'] = "Seleccione sí para requerir este campo. Tenga en cuenta que las reglas de validación especiales se pueden utilizar para este campo en Reglas de entrada.";
$lang['UniversalServerModule.!tooltip.option_heading_field_encrypt'] = "Selección de sí hará que los datos de campo que se almacenan encriptados. Los datos serán sin cifrar automáticamente para la visualización cuando sea necesario.";
$lang['UniversalServerModule.!tooltip.option_heading_notice_notice'] = "Introduzca la URL para su anuncio, o la dirección de correo electrónico para enviar por correo electrónico para esta acción.";
$lang['UniversalServerModule.!tooltip.option_heading_notice_response'] = "Si la publicación a una URL, puede introducir una palabra o frase contenida en la respuesta que indica un éxito.";

$lang['UniversalServerModule.moreinfo'] = "Mas Informacion";
$lang['UniversalServerModule.hostname'] = "Hostname";
$lang['UniversalServerModule.operativesystem'] = "Sistema Operativo";
$lang['UniversalServerModule.ssh_console'] = "Consola Web SSH";
$lang['UniversalServerModule.ftp_client'] = "Cliente Web FTP";
$lang['UniversalServerModule.server_stats'] = "Estadisticas";
$lang['UniversalServerModule.dont_connect'] = "No se pudo conectar a";
$lang['UniversalServerModule.server_information'] = "Informacion del Servidor";
$lang['UniversalServerModule.server_whois'] = "Whois IP Principal del Servidor";
$lang['UniversalServerModule.server'] = "Servidor";
$lang['UniversalServerModule.user'] = "Usuario";
$lang['UniversalServerModule.pass'] = "Contraseña";
$lang['UniversalServerModule.port'] = "Puerto";
$lang['UniversalServerModule.connect'] = "Conectar";
$lang['UniversalServerModule.active'] = "Activo";
$lang['UniversalServerModule.down'] = "Inactivo";
$lang['UniversalServerModule.retry'] = "Reintentar";
$lang['UniversalServerModule.last_update'] = "Ultima Actualizacion: ";
$lang['UniversalServerModule.server_tools_not_installed'] = "CyanDark ServerTools No esta Instalado";
$lang['UniversalServerModule.server_tools_not_installed_desc'] = "CyanDark ServerTools No se encuentra instalado en el servidor. <br><br> CyanDark ServerTools es una herramienta diseñada para obtener informacion y estadisticas en tiempo real respecto al estado del Servidor. <br><br> Esta herramientra requiere de un stack (Apache y PHP) instalado en el Sistema Operativo y priviliegios de Super Usuario para funcionar correctamente. <br><br> Para instalar CyanDark ServerTools debes instalar un Stack LAMP (Algunos Sistemas Operativos como Cent OS lo traen por defecto). Una vez corroborada la instalacion del Stack, Buscar la carpeta correspondiente donde se alojan los archivos publicos (Esto Cambia segun el Sistema Operativo y Panel de Control instalado en el sistema). <br><br> Una vez dentro de la carpeta, Ejecutar los siguientes comandos: <br><br><font style=\"color: ccc !important; font-family: 'Inconsolata';\"><i>$ wget https://clients.cyandark.com/servertools.zip</i></font> <br><font style=\"color: ccc !important; font-family: 'Inconsolata';\"><i>$ unzip servertools.zip</i></font> <br><br> Una vez instalado, El archivo debe ser accesible desde http://DED_IP/tools.php. <br><br> Esta notificacion desaparecera automaticamente al detectarse CyanDark ServerTools Instalado.<br><br><b>Nota:</b> Esta herramienta unicamente funciona en Sistemas Operativos basados en RHEL. No funciona en Debian o Windows.";
$lang['UniversalServerModule.recover_pass'] = "Recuperar Contraseña";
$lang['UniversalServerModule.change_pass'] = "Cambiar Contraseña";
$lang['UniversalServerModule.control_panel'] = "Panel de Control";
$lang['UniversalServerModule.on'] = "Encender";
$lang['UniversalServerModule.off'] = "Apagar";
$lang['UniversalServerModule.reset'] = "Reiniciar";
$lang['UniversalServerModule.on_button'] = "Boton de Encendido";
$lang['UniversalServerModule.off_button'] = "Boton de Apagado";
$lang['UniversalServerModule.reset_button'] = "Boton de Reinicio";
$lang['UniversalServerModule.colocation'] = "Colocacion";
$lang['UniversalServerModule.datacenter'] = "Centro de Datos";
$lang['UniversalServerModule.ubication'] = "Ubicacion";
$lang['UniversalServerModule.position'] = "Posicion";
$lang['UniversalServerModule.weight'] = "Peso";
$lang['UniversalServerModule.bandwidth'] = "Uso de Red";
$lang['UniversalServerModule.month'] = "Mes";
$lang['UniversalServerModule.week'] = "Semana";
$lang['UniversalServerModule.day'] = "Día";

$lang['UniversalServerModule.add_row.custom_fields'] = "Parametros Personalizados";

$lang['UniversalServerModule.add_row.remove_colocation'] = "Remover Colocation";
$lang['UniversalServerModule.server_on_ok'] = 'El servidor se Encendio Correctamente.';
$lang['UniversalServerModule.server_on_error'] = 'El servidor no pudo Iniciarse.';
$lang['UniversalServerModule.server_off_ok'] = 'El servidor se Apago Correctamente.';
$lang['UniversalServerModule.server_off_error'] = 'El Servidor no pugo Apagarse.';
$lang['UniversalServerModule.server_reset_ok'] = 'El servidor se Reinicio Correctamente.';
$lang['UniversalServerModule.server_reset_error'] = 'El servidor no pudo Reiniciarse.';
$lang['UniversalServerModule.add_row.advanced_settings'] = 'Configuracion Avanzada';
?>